apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-deployment
  namespace: congthanh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: congthanh19/regapp:${BUILD_NUMBER} 
        ports:
        - containerPort: 8080